alias showpath="echo $PATH | tr ':' '\n'"
alias duh="sudo du -h --one-file-system --max-depth=1 --threshold=100K | sort -h"
alias hs="history | grep -i"

alias la="ls -la"
alias lah="ls -lah"

alias dc="docker-compose"
alias dcu="docker-compose up -d"
alias dcd="docker-compose down"
alias dps="docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Networks}}\t{{.Status}}'"
alias dl="docker logs -f"

alias ga="git add"
alias gp="git push"
alias gc="git commit"
alias gf="git fetch"
alias gd="git diff"
alias gds="git diff --staged"
alias gst="git status"
